export const productActons={
    SET_PRODUCT:"SET_PRODUCT",
    SELECT_PRODUCT:"SELECT_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT"
}
export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_TO_CART="REMOVE_TO_CART";
export const DELETE_FROM_CART="DELETE_FROM_CART";